
# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

global: {ngcImagePullSecretName: ""}
nvcf:
  dockerRegSecrets: []
  additionalSecrets: []
  localStorageProvisioner: []
vss:
  applicationSpecs:
    vss-deployment:
      containers:
        vss:
          env:
          - name: VLM_MODEL_TO_USE
            value: cosmos-reason2
          - name: MODEL_PATH
            value: git:https://huggingface.co/nvidia/Cosmos-Reason2-8B
          - name: DISABLE_GUARDRAILS
            value: 'false'
          - name: OPENAI_API_KEY_NAME
            value: VSS_OPENAI_API_KEY
          - name: NVIDIA_API_KEY_NAME
            value: VSS_NVIDIA_API_KEY
          - name: NGC_API_KEY_NAME
            value: VSS_NGC_API_KEY
          - name: TRT_LLM_MODE
            value: int4_awq
          - name: VLM_BATCH_SIZE
            value: ''
          - name: VIA_VLM_OPENAI_MODEL_DEPLOYMENT_NAME
            value: ''
          - name: VIA_VLM_ENDPOINT
            value: ''
          - name: VIA_VLM_API_KEY
            value: ''
          - name: OPENAI_API_VERSION
            value: ''
          - name: AZURE_OPENAI_API_VERSION
            value: ''
          - name: ENABLE_AUDIO
            value: 'false'
          - name: LLM_MODEL
            value: meta/llama-3.1-70b-instruct
          - name: RIVA_ASR_SERVER_URI
            value: riva-service
          - name: RIVA_ASR_GRPC_PORT
            value: '50051'
          - name: RIVA_ASR_HTTP_PORT
            value: '9000'
          - name: ENABLE_RIVA_SERVER_READINESS_CHECK
            value: 'false'
          - name: RIVA_ASR_SERVER_IS_NIM
            value: 'true'
          - name: RIVA_ASR_SERVER_USE_SSL
            value: 'false'
          - name: RIVA_ASR_SERVER_API_KEY
            value: ''
          - name: RIVA_ASR_SERVER_FUNC_ID
            value: ''
          - name: INSTALL_PROPRIETARY_CODECS
            value: 'false'
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z -w 2 milvus-milvus-deployment-milvus-service 19530; do echo
          waiting for milvus; sleep 2; done
        image: busybox:1.37
        imagePullPolicy: IfNotPresent
        name: check-milvus-up
      - command:
        - sh
        - -c
        - until nc -z -w 2 neo-4-j-service 7687; do echo waiting for neo4j; sleep
          2; done
        image: busybox:1.37
        imagePullPolicy: IfNotPresent
        name: check-neo4j-up
      - args:
        - "while ! curl -s -f -o /dev/null http://llm-nim-svc:8000/v1/health/live;\
          \ do\n  echo \"Waiting for LLM...\"\n  sleep 2\ndone\n"
        command:
        - sh
        - -c
        image: curlimages/curl:8.17.0
        name: check-llm-up
  resources:
    limits:
      nvidia.com/gpu: 2

  vlmModelPath: git:https://huggingface.co/nvidia/Cosmos-Reason2-8B
  vlmModelType: cosmos-reason2
  workloadSpecs:
    wl-env:
      wl_env:
      - name: FRONTEND_PORT
        value: '9000'
      - name: BACKEND_PORT
        value: '8000'
      - name: GRAPH_DB_HOST
        value: neo-4-j-service
      - name: GRAPH_DB_PORT
        value: '7687'
      - name: MILVUS_DB_HOST
        value: milvus-milvus-deployment-milvus-service
      - name: MILVUS_DB_PORT
        value: '19530'
      - name: MINIO_HOST
        value: minio-minio-deployment-minio-service
      - name: MINIO_PORT
        value: '9000'
      - name: MINIO_WEBUI_PORT
        value: '9001'
      - name: ARANGO_DB_HOST
        value: arango-db-arango-db-deployment-arango-db-service
      - name: ARANGO_DB_PORT
        value: '8529'
      - name: APP_VECTORSTORE_URL
        value: http://milvus-milvus-deployment-milvus-service:19530
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            key: OPENAI_API_KEY
            name: openai-api-key-secret
            optional: true
      - name: NGC_API_KEY
        valueFrom:
          secretKeyRef:
            key: NGC_API_KEY
            name: ngc-api-key-secret
      - name: NVIDIA_API_KEY
        valueFrom:
          secretKeyRef:
            key: NVIDIA_API_KEY
            name: nvidia-api-key-secret
            optional: true
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            key: HF_TOKEN
            name: hf-token-secret
            optional: true
      - name: GRAPH_DB_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: graph-db-creds-secret
      - name: GRAPH_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: graph-db-creds-secret
      - name: MINIO_USERNAME
        valueFrom:
          secretKeyRef:
            key: access-key
            name: minio-creds-secret
      - name: MINIO_PASSWORD
        valueFrom:
          secretKeyRef:
            key: secret-key
            name: minio-creds-secret
      - name: ARANGO_DB_USERNAME
        valueFrom:
          secretKeyRef:
            key: username
            name: arango-db-creds-secret
      - name: ARANGO_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            key: password
            name: arango-db-creds-secret
      - name: ES_HOST
        value: elasticsearch-elasticsearch-deployment-elasticsearch-service
      - name: ES_PORT
        value: '9200'
      - name: ES_TRANSPORT_PORT
        value: '9300'
  configs:
    ca_rag_config.yaml:
      tools:
        chat_llm:
          params:
            base_url: http://llm-nim-svc:8000/v1
        notification_llm:
          params:
            base_url: http://llm-nim-svc:8000/v1
        nvidia_embedding:
          params:
            base_url: http://nemo-embedding-embedding-deployment-embedding-service:8000/v1
        nvidia_reranker:
          params:
            base_url: http://nemo-rerank-ranking-deployment-ranking-service:8000/v1
        summarization_llm:
          params:
            base_url: http://llm-nim-svc:8000/v1
    guardrails_config.yaml:
      models:
      - engine: nim
        model: meta/llama-3.1-70b-instruct
        parameters:
          base_url: http://llm-nim-svc:8000/v1
        type: main
      - engine: nim
        model: nvidia/llama-3.2-nv-embedqa-1b-v2
        parameters:
          base_url: http://nemo-embedding-embedding-deployment-embedding-service:8000/v1
        type: embeddings
  egress:
    milvus:
      address: milvus-milvus-deployment-milvus-service
      port: 19530
    neo4j-bolt:
      address: neo-4-j-service
      port: 7687
    llm-openai-api:
      address: llm-nim-svc
      port: 8000
    nemo-embed:
      address: nemo-embedding-embedding-deployment-embedding-service
      port: 8000
    nemo-rerank:
      address: nemo-rerank-ranking-deployment-ranking-service
      port: 8000
    riva-api:
      address: riva-service
      port: 9000
    arango-db:
      address: arango-db-arango-db-deployment-arango-db-service
      port: 8529
    minio:
      address: minio-minio-deployment-minio-service
      port: 9000
    elasticsearch:
      address: elasticsearch-elasticsearch-deployment-elasticsearch-service
      port: 9200
etcd:
  enabled: true
milvus-minio:
  enabled: true
milvus:
  applicationSpecs:
    milvus-deployment:
      containers:
        milvus-container:
          env:
          - name: ETCD_ENDPOINTS
            value: etcd-etcd-deployment-etcd-service:2379
          - name: MINIO_ADDRESS
            value: milvus-minio-milvus-minio-deployment-milvus-minio-service:9010
          - name: KNOWHERE_GPU_MEM_POOL_SIZE
            value: 2048;4096
  enabled: true
  egress:
    etcd:
      address: etcd-etcd-deployment-etcd-service
      port: 2379
    milvus-minio:
      address: milvus-minio-milvus-minio-deployment-milvus-minio-service
      port: 9010
neo4j:
  enabled: true
  extraPodVolumes:
  - name: secret-db-username-volume
    secret:
      secretName: graph-db-creds-secret
      items:
      - key: username
        path: db-username
  - name: secret-db-password-volume
    secret:
      secretName: graph-db-creds-secret
      items:
      - key: password
        path: db-password
  extraPodVolumeMounts:
  - name: secret-db-username-volume
    mountPath: /secrets/db-username
    subPath: db-username
    readOnly: true
  - name: secret-db-password-volume
    mountPath: /secrets/db-password
    subPath: db-password
    readOnly: true
nim-llm:
  env:
  - name: NIM_MAX_MODEL_LEN
    value: '128000'
  image:
    repository: nvcr.io/nim/meta/llama-3.1-70b-instruct
    tag: 1.10.1
  resources:
    limits:
      nvidia.com/gpu: 4
  model:
    name: meta/llama-3.1-70b-instruct
    ngcAPISecret: ngc-api-key-secret
    tag: 1.10.1
  persistence:
    enabled: true
  hostPath:
    enabled: true
  service:
    name: llm-nim-svc
  llmModel: meta/llama-3.1-70b-instruct
  llmTag: 1.10.1
  enabled: true
nemo-embedding:
  resources:
    limits:
      nvidia.com/gpu: 1

  enabled: true
nemo-rerank:
  resources:
    limits:
      nvidia.com/gpu: 1

  enabled: true
riva:
  enabled: false
arango-db:
  enabled: true
  extraPodVolumes:
  - name: secret-db-username-volume
    secret:
      secretName: arango-db-creds-secret
      items:
      - key: username
        path: db-username
  - name: secret-db-password-volume
    secret:
      secretName: arango-db-creds-secret
      items:
      - key: password
        path: db-password
  extraPodVolumeMounts:
  - name: secret-db-username-volume
    mountPath: /secrets/db-username
    subPath: db-username
    readOnly: true
  - name: secret-db-password-volume
    mountPath: /secrets/db-password
    subPath: db-password
    readOnly: true
minio:
  enabled: true
  extraPodVolumes:
  - name: secret-access-key-volume
    secret:
      secretName: minio-creds-secret
      items:
      - key: access-key
        path: access-key
  - name: secret-secret-key-volume
    secret:
      secretName: minio-creds-secret
      items:
      - key: secret-key
        path: secret-key
  extraPodVolumeMounts:
  - name: secret-access-key-volume
    mountPath: /secrets/access-key
    subPath: access-key
    readOnly: true
  - name: secret-secret-key-volume
    mountPath: /secrets/secret-key
    subPath: secret-key
    readOnly: true
elasticsearch:
  enabled: true
