# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

Component:
  app-version: 2.1.0
  description: ArangoDB multi-model database with vector index support
  helmUrlLocationPath: https://helm.ngc.nvidia.com/myorg/myteam/charts
  name: arango-db
  version: 2.1.0
affinity: {}
applicationSpecs:
  arango-db-deployment:
    apptype: stateless
    containers:
      arango-db-container:
        args:
        - arangod
        - --experimental-vector-index
        - --server.endpoint
        - http://0.0.0.0:8529
        env:
        - name: ARANGO_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: arango-db-creds-secret
        - name: ARANGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: arango-db-creds-secret
        image:
          repository: arangodb
          tag: 3.12.6
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_admin/server/availability
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
        ports:
        - containerPort: 8529
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_admin/server/availability
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
    services:
      arango-db-service:
        ports:
        - name: http-api
          port: 8529
defaultVolumeMounts:
- mountPath: /opt/workload-config
  name: workload-cm-volume
- mountPath: /opt/configs
  name: configs-volume
- mountPath: /opt/scripts
  name: scripts-cm-volume
defaultVolumes:
- configMap:
    name: arango-db-workload-cm
  name: workload-cm-volume
- configMap:
    name: arango-db-configs-cm
  name: configs-volume
- configMap:
    name: arango-db-scripts-cm
  name: scripts-cm-volume
egress: {}
externalFiles: []
image:
  pullPolicy: IfNotPresent
imagePullSecrets: []
ingress:
  enabled: false
metrics: {}
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
storageClaims: {}
tolerations: []
workloadSpecs:
  dummy: {}



configs:
  config.yaml:
    SampleConfig:
      sampleValue: 0

