# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved.
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

Component:
  app-version: 2.1.0
  description: ElasticSearch database service for search and analytics
  helmUrlLocationPath: https://helm.ngc.nvidia.com/myorg/myteam/charts
  name: elasticsearch
  version: 2.1.0
affinity: {}
applicationSpecs:
  elasticsearch-deployment:
    apptype: stateless
    containers:
      elasticsearch-container:
        env:
        - name: discovery.type
          value: single-node
        - name: xpack.security.enabled
          value: 'false'
        - name: ES_JAVA_OPTS
          value: -Xms6g -Xmx6g
        image:
          repository: elasticsearch
          tag: 9.2.1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            memory: 16Gi
          requests:
            cpu: '1'
            memory: 16Gi
    services:
      elasticsearch-service:
        ports:
        - name: http-api
          port: 9200
        - name: http-transport
          port: 9300
defaultVolumeMounts:
- mountPath: /opt/workload-config
  name: workload-cm-volume
- mountPath: /opt/configs
  name: configs-volume
- mountPath: /opt/scripts
  name: scripts-cm-volume
defaultVolumes:
- configMap:
    name: elasticsearch-workload-cm
  name: workload-cm-volume
- configMap:
    name: elasticsearch-configs-cm
  name: configs-volume
- configMap:
    name: elasticsearch-scripts-cm
  name: scripts-cm-volume
egress: {}
externalFiles: []
image:
  pullPolicy: IfNotPresent
imagePullSecrets: []
ingress:
  enabled: false
metrics: {}
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
storageClaims: {}
tolerations: []
workloadSpecs:
  dummy: {}



configs:
  config.yaml:
    SampleConfig:
      sampleValue: 0

