apiVersion: v2
name: video-search-and-summarization
description: A Helm chart for Video Search and Summarization
icon: https://avatars.githubusercontent.com/u/33164907
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: nvidia-blueprint-vss
    version: 2.4.1
